# Generated by Django 4.2 on 2023-04-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magcalendar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_exercises',
            name='id_Exercises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magcalendar.exercises'),
        ),
    ]
