# Generated by Django 4.2 on 2023-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magcalendar', '0006_exercises_photo_url_alter_exercises_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='photo_url',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
