# Generated by Django 4.2 on 2023-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magcalendar', '0008_exercises_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='note',
            field=models.CharField(default='notatka', max_length=255),
        ),
        migrations.AddField(
            model_name='exercises',
            name='video_url',
            field=models.CharField(default='default.html', max_length=255),
        ),
    ]
